apiVersion: v1
kind: Service
metadata:
  name: chenkangtest-maven-svc
  namespace: chenkang
spec:
  selector:
    app: chenkangtestnginx
  type: ClusterIP
  ports:
  - name: chenkang-test
    port: 8080
    targetPort: 8080
